//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTroChuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiVietBaoCao
    {
        public int ID { get; set; }
        public Nullable<int> BaiVietID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string LyDoBaoCao { get; set; }
        public Nullable<System.DateTime> NgayBaoCao { get; set; }
        public string TrangThai { get; set; }
    
        public virtual BaiViet BaiViet { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
