//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTroChuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int BinhLuanID { get; set; }
        public int BaiVietID { get; set; }
        public int UserID { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayBinhLuan { get; set; }
    
        public virtual BaiViet BaiViet { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
