//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTroChuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int MaChat { get; set; }
        public int UserID { get; set; }
        public string TinNhan { get; set; }
        public System.DateTime ThoiGianGui { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
